[versions]

[libraries]
firebase-analytics = "com.google.firebase:firebase-analytics-ktx:21.2.2"
firebase-crashlytics-ktx = "com.google.firebase:firebase-crashlytics-ktx:18.3.6"
firebase-crashlytics-gradle = "com.google.firebase:firebase-crashlytics-gradle:2.9.5"

simularity = "info.debatty:java-string-similarity:2.0.0"
xlog = "com.elvishew:xlog:1.11.0"

ratingbar = "me.zhanghai.android.materialratingbar:library:1.4.0"
composeRatingbar = "com.github.a914-gowtham:compose-ratingbar:1.2.3"

versionsx = "com.github.ben-manes:gradle-versions-plugin:0.42.0"