name: CI
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  build:
    name: Build app
    needs: check_wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Build app
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleDevDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: TachiyomiSY-${{ github.sha }}.apk
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk
